In [22]:
import numpy as np
import pandas as pd


df = pd.DataFrame(
    {
        'years': [1, 2, 3, 4, 5, 6],
        'salary': [4000, 4250, 4500, 4750, 5000, 5250],
    }
)
X1=df['years']
Y=df['salary']
X = np.c_[np.ones((6, 1)), X1]

coefs=np.dot(np.linalg.inv(np.dot(X.T,X)),np.dot(X.T,Y))
print(f'Linear regression: {coefs[0]:.2f} + {coefs[1]:.2f}x')   




Linear regression: 3750.00 + 250.00x


In [45]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
 
 
df = pd.read_csv('data.csv')
data=df[['variable']]
target=df['target']
data
lr=LinearRegression()
lr.fit(data,target)
print(f'{lr.score(data,target):.4f}')   

0.5532


In [48]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
 
 
np.set_printoptions(suppress=True, precision=3)
df = pd.read_csv('data.csv')
data=df[['var1']]
pf=PolynomialFeatures(degree=2)
pf.fit(data)
data_poly=pf.transform(data)
data_poly

array([[ 1.   , -0.542,  0.294],
       [ 1.   ,  0.529,  0.279],
       [ 1.   ,  0.625,  0.391],
       [ 1.   ,  0.194,  0.038],
       [ 1.   , -0.8  ,  0.64 ],
       [ 1.   , -0.304,  0.092],
       [ 1.   ,  1.086,  1.18 ],
       [ 1.   , -1.16 ,  1.346],
       [ 1.   ,  1.038,  1.078],
       [ 1.   , -0.815,  0.665],
       [ 1.   ,  0.416,  0.173],
       [ 1.   ,  1.297,  1.683],
       [ 1.   , -0.433,  0.187],
       [ 1.   ,  1.059,  1.121],
       [ 1.   ,  1.139,  1.297],
       [ 1.   ,  1.   ,  1.   ],
       [ 1.   ,  0.109,  0.012],
       [ 1.   , -0.39 ,  0.152],
       [ 1.   , -0.701,  0.491],
       [ 1.   ,  0.698,  0.488],
       [ 1.   ,  0.752,  0.565],
       [ 1.   ,  0.661,  0.437],
       [ 1.   , -0.964,  0.93 ],
       [ 1.   , -0.252,  0.064],
       [ 1.   ,  0.344,  0.119],
       [ 1.   ,  0.524,  0.274],
       [ 1.   , -0.164,  0.027],
       [ 1.   ,  0.048,  0.002],
       [ 1.   ,  0.606,  0.367],
       [ 1.   , -0.148,  0.022]])

In [49]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
 
 
np.set_printoptions(suppress=True, precision=3)
df = pd.read_csv('data.csv')
data=df[['var1','var2']]
pf=PolynomialFeatures(degree=3)
pf.fit(data)
data_poly=pf.transform(data)
data_poly

array([[  1.   ,  -0.016,   0.589,   0.   ,  -0.01 ,   0.347,  -0.   ,
          0.   ,  -0.006,   0.204],
       [  1.   ,   0.754,   0.076,   0.569,   0.058,   0.006,   0.429,
          0.043,   0.004,   0.   ],
       [  1.   ,  -1.157,  -1.465,   1.338,   1.695,   2.146,  -1.548,
         -1.96 ,  -2.482,  -3.143],
       [  1.   ,   0.177,  -0.175,   0.031,  -0.031,   0.031,   0.006,
         -0.006,   0.005,  -0.005],
       [  1.   ,  -2.502,   1.536,   6.258,  -3.843,   2.36 , -15.656,
          9.615,  -5.905,   3.626],
       [  1.   ,   0.631,   0.537,   0.398,   0.339,   0.288,   0.251,
          0.214,   0.182,   0.155],
       [  1.   ,   0.239,   0.227,   0.057,   0.054,   0.051,   0.014,
          0.013,   0.012,   0.012],
       [  1.   ,   1.062,   0.598,   1.127,   0.635,   0.358,   1.197,
          0.675,   0.38 ,   0.214],
       [  1.   ,  -0.837,  -0.328,   0.7  ,   0.275,   0.108,  -0.586,
         -0.23 ,  -0.09 ,  -0.035],
       [  1.   ,   0.567,  -0.313,   

In [58]:
import numpy as np
import pandas as pd

data = pd.read_csv('data.csv')

MAE=np.mean((data['y_true'].values-data['y_pred'].values)**2)
print(f'MAE = {MAE:.6}')

MAE = 74.9471


In [62]:
import numpy as np
import pandas as pd


np.random.seed(42)
df = pd.DataFrame(data=np.random.randn(10), columns=['var1'])

def sigmoid(x):
    return 1/(1+np.exp(-x))

df['var1_sigmoid']=sigmoid(df['var1'])
print(df)

var1  var1_sigmoid
0  0.496714      0.621687
1 -0.138264      0.465489
2  0.647689      0.656489
3  1.523030      0.820984
4 -0.234153      0.441728
5 -0.234137      0.441732
6  1.579213      0.829093
7  0.767435      0.682966
8 -0.469474      0.384741
9  0.542560      0.632408

In [63]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.set_printoptions(precision=4, suppress=True)
data=pd.read_csv('data.csv')

scaler=StandardScaler()
data_transformed=scaler.fit_transform(data)
print(data_transformed) 

[[-0.4785 -0.2137 -0.4584 -0.5114  0.0636]
 [ 1.3742  0.3895  1.2924  1.4055 -0.616 ]
 [ 0.3777 -0.0178  0.3905  0.2783  0.7424]
 [-0.4986 -0.4185 -0.4427 -0.5531  0.4723]
 [-0.7449 -1.1397 -0.7236 -0.745   0.0771]
 [ 1.8496  2.1747  1.9719  1.8048  1.3537]
 [ 2.2534  0.5208  2.2644  2.4466  0.5363]
 [ 0.9819 -1.0039  0.9382  0.8882 -0.0203]
 [-0.2294 -0.8236 -0.236  -0.3987  0.6429]
 [-0.069  -0.6544 -0.1338 -0.1639 -2.1663]
 [-0.2666  1.2665 -0.3344 -0.3457 -0.7709]
 [ 0.7557 -0.1692  0.7035  0.6847 -0.7183]
 [ 0.2374  0.0445  0.1351  0.1047 -1.0339]
 [ 0.6068  0.5164  0.6293  0.5087  1.2613]
 [-0.5158 -1.6227 -0.5469 -0.551  -0.6202]
 [ 1.4201  1.498   1.5189  1.4114  1.6167]
 [ 0.1916 -1.0818  0.1005  0.0766 -0.9977]
 [-1.14    0.0066 -1.1321 -1.0148  0.1098]
 [-2.0504 -1.3645 -1.9945 -1.5123  1.2968]
 [ 1.8353  0.2893  1.8772  1.932   0.4154]
 [-0.0977 -0.8392 -0.0737 -0.2091  0.1382]
 [-0.5845 -0.4096 -0.5827 -0.617   0.2946]
 [ 2.1388  0.6054  2.149   2.2248  1.2755]
 [-1.1773  

In [69]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.set_printoptions(precision=4, suppress=True)

X_train=pd.read_csv('X_train.csv')
X_test=pd.read_csv('X_test.csv')
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

print(X_train_scaled[:5])
print(X_test_scaled[:5])

[[-0.3491 -1.4385 -0.4117 -0.3905 -1.8637]
 [-0.2047  0.3126 -0.1337 -0.2759  1.0781]
 [-0.3293 -0.2151 -0.3174 -0.3644 -1.5799]
 [ 1.0274  2.0898  1.0469  0.9176  0.3163]
 [ 1.829   0.696   1.7637  1.7838 -0.3337]]
[[-0.4681 -0.1417 -0.4447 -0.486   0.2934]
 [ 1.3645  0.4996  1.3064  1.3344 -0.3917]
 [ 0.3788  0.0665  0.4043  0.264   0.9777]
 [-0.4879 -0.3594 -0.429  -0.5256  0.7054]
 [-0.7315 -1.1261 -0.71   -0.7079  0.307 ]]


In [99]:
import numpy as np
import pandas as pd


def entropy(x):
    return np.round(-np.sum(x * np.log2(x)), 4)


df = pd.DataFrame(
    {
        'val_1': np.arange(0.01, 1.0, 0.1),
        'val_2': 1 - np.arange(0.01, 1.0, 0.1),
    }
)


for i in range(len(df)):
    df.loc[i,'entropy']=entropy([df.loc[i,'val_1'],df.loc[i,'val_2']])
print(df)


   val_1  val_2  entropy
0   0.01   0.99   0.0808
1   0.11   0.89   0.4999
2   0.21   0.79   0.7415
3   0.31   0.69   0.8932
4   0.41   0.59   0.9765
5   0.51   0.49   0.9997
6   0.61   0.39   0.9648
7   0.71   0.29   0.8687
8   0.81   0.19   0.7015
9   0.91   0.09   0.4365


In [104]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
data=pd.read_csv('predictions.csv')
acc=accuracy_score(data['y_true'],data['y_pred'])
conf=confusion_matrix(data['y_true'],data['y_pred'])

c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\utils\_array_api.py:245: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)


ValueError: Input y_pred contains NaN.

In [108]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)
classifier=DecisionTreeClassifier(max_depth=6,min_samples_leaf=6)
classifier.fit(X_train,y_train)
acc=classifier.score(X_test,y_test) 
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.9300


In [113]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)
classifier=DecisionTreeClassifier()
params={'max_depth':np.arange(1,10),'min_samples_leaf':[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20],}
grid=GridSearchCV(classifier,params,cv=5,scoring='accuracy')
grid.fit(X_train,y_train)   
print(grid.best_params_)

{'max_depth': 6, 'min_samples_leaf': 6}


In [2]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)
classifier=RandomForestClassifier(random_state=42)
classifier.fit(X_train,y_train)
acc=classifier.score(X_test,y_test)
print(f'Accuracy: {acc:.4f}')

Accuracy: 0.9300


In [11]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)
classifier=RandomForestClassifier()

params={'max_depth':[6,7], 'min_samples_leaf':[4,5],'criterion':['gini','entropy']}
grid=GridSearchCV(classifier,params,cv=5,scoring='accuracy')
grid.fit(X_train,y_train)
acc=grid.score(X_test,y_test)   
print(grid.best_params_)

{'criterion': 'entropy', 'max_depth': 7, 'min_samples_leaf': 5}
