In [11]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer


documents = [
    'python is a programming language',
    'python is popular',
    'programming in python',
    'object-oriented programming in python'
]

vectorizer=CountVectorizer(stop_words='english',ngram_range=(1,2))
vectorizer.fit(documents)
df = pd.DataFrame(
    data=vectorizer.fit_transform(documents).toarray(),
    columns=vectorizer.get_feature_names_out())

print(df)


   language  object  object oriented  oriented  oriented programming  popular  \
0         1       0                0         0                     0        0   
1         0       0                0         0                     0        1   
2         0       0                0         0                     0        0   
3         0       1                1         1                     1        0   

   programming  programming language  programming python  python  \
0            1                     1                   0       1   
1            0                     0                   0       1   
2            1                     0                   1       1   
3            1                     0                   1       1   

   python popular  python programming  
0               0                   1  
1               1                   0  
2               0                   0  
3               0                   0  


In [14]:
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer




documents = [
    'python is a programming language',
    'python is popular',
    'programming in python',
    'object-oriented programming in python',
    'programming language'
]

vectorizer = TfidfVectorizer(stop_words=['is','in'])
df=pd.DataFrame(data=vectorizer.fit_transform(documents).toarray(),columns=vectorizer.get_feature_names_out())
print(df )

   language    object  oriented   popular  programming    python
0  0.711525  0.000000  0.000000  0.000000     0.496856  0.496856
1  0.000000  0.000000  0.000000  0.871247     0.000000  0.490845
2  0.000000  0.000000  0.000000  0.000000     0.707107  0.707107
3  0.000000  0.616065  0.616065  0.000000     0.347080  0.347080
4  0.819887  0.000000  0.000000  0.000000     0.572526  0.000000


In [74]:
import numpy as np
from numpy.linalg import norm
import pandas as pd
import random


np.random.seed(42)
data_raw=pd.read_csv('data.csv')
min_x1=min(data_raw['x1'])
max_x1=max(data_raw['x1'])
min_x2=min(data_raw['x2'])
max_x2=max(data_raw['x2'])    
centroid1=[random.uniform(min_x1,max_x1),random.uniform(min_x2,max_x2)]
centroid2=[random.uniform(min_x1,max_x1),random.uniform(min_x2,max_x2)]
#print(centroid1,centroid2)
for i in range(0,10):
    data_raw['dist1']=norm(data_raw[['x1','x2']]-centroid1,axis=1)
    data_raw['dist2']=norm(data_raw[['x1','x2']]-centroid2,axis=1)
    data_raw['cluster']=np.where(data_raw['dist1']<data_raw['dist2'],1,2)
    tempx1=data_raw[data_raw['cluster']==1]['x1']
    tempx2=data_raw[data_raw['cluster']==1]['x2']
    centroid1=[tempx1.values.sum()/len(tempx1), tempx2.values.sum()/len(tempx2)] 
    tempx1=data_raw[data_raw['cluster']==2]['x1']
    tempx2=data_raw[data_raw['cluster']==2]['x2']
    centroid2=[tempx1.values.sum()/len(tempx1), tempx2.values.sum()/len(tempx2)] 
    print(f'Iteracja {i} centroid1: {centroid1}, centroind2 {centroid2}')

Iteracja 0 centroid1: [2.277925978589282, 1.4238109865487707], centroind2 [1.2154173629196332, -0.940860909988089]
Iteracja 1 centroid1: [0.5076646452504974, 2.7977017256629315], centroind2 [2.325742076120114, -2.817348936343221]
Iteracja 2 centroid1: [0.35237492115444785, 2.5020478929692644], centroind2 [2.6628395433031256, -3.08320016985017]
Iteracja 3 centroid1: [0.35237492115444785, 2.5020478929692644], centroind2 [2.6628395433031256, -3.08320016985017]
Iteracja 4 centroid1: [0.35237492115444785, 2.5020478929692644], centroind2 [2.6628395433031256, -3.08320016985017]
Iteracja 5 centroid1: [0.35237492115444785, 2.5020478929692644], centroind2 [2.6628395433031256, -3.08320016985017]
Iteracja 6 centroid1: [0.35237492115444785, 2.5020478929692644], centroind2 [2.6628395433031256, -3.08320016985017]
Iteracja 7 centroid1: [0.35237492115444785, 2.5020478929692644], centroind2 [2.6628395433031256, -3.08320016985017]
Iteracja 8 centroid1: [0.35237492115444785, 2.5020478929692644], centroind

In [88]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans


np.random.seed(42)
wcss=[]
data_raw=pd.read_csv('clusters.csv')
for i in(range(2,10)):
    cluster=KMeans(n_clusters=i,random_state=42)
    cluster.fit(data_raw[['x1','x2']])  
    wcss.append(round(cluster.inertia_,2))
print(wcss)

c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are

[23414.04, 7734.89, 4282.14, 3866.72, 3442.86, 3120.69, 2716.96, 2469.26]


In [89]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans


np.random.seed(42)
df = pd.read_csv('clusters.csv')

wcss = []
for i in range(2, 10):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(df)
    wcss.append(round(kmeans.inertia_, 2))
print('3' )   

c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(
c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)
c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are

[23414.04, 7734.89, 4282.14, 3866.72, 3442.86, 3120.69, 2716.96, 2469.26]


In [94]:
import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

df=pd.read_csv('clusters.csv')
cluster=AgglomerativeClustering(n_clusters=2,affinity='manhattan',linkage='complete')
df['cluster']=cluster.fit_predict(df)
print(df[:10])

         x1        x2  cluster
0 -2.486532  7.025770        0
1 -3.522549  8.578303        0
2 -2.982040  7.998514        0
3 -2.135276  6.255888        0
4  2.762504  4.210918        1
5 -3.541472  8.489106        0
6  1.240259  0.781640        1
7  0.053390  8.966770        0
8 -0.827918  6.742253        0
9  3.291716  1.296751        1


c:\Users\tkdar\anaconda3\Lib\site-packages\sklearn\cluster\_agglomerative.py:1005: FutureWarning: Attribute `affinity` was deprecated in version 1.2 and will be removed in 1.4. Use `metric` instead
  warnings.warn(


In [100]:
from sklearn.cluster import DBSCAN

df=pd.read_csv('clusters.csv')
cluster=DBSCAN(eps=0.6,min_samples=7)
df['cluster']=cluster.fit_predict(df) 
print(df.cluster.value_counts())

AttributeError: 'DBSCAN' object has no attribute 'value_counts'

In [104]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


df=pd.read_csv('pca.csv')
X=df[['var1','var2','var3']]
y=df['class']
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
print(X_scaled[:10])

[[-0.90068117 -1.34022653 -1.3154443 ]
 [-1.14301691 -1.34022653 -1.3154443 ]
 [-1.38535265 -1.39706395 -1.3154443 ]
 [-1.50652052 -1.2833891  -1.3154443 ]
 [-1.02184904 -1.34022653 -1.3154443 ]
 [-0.53717756 -1.16971425 -1.05217993]
 [-1.50652052 -1.34022653 -1.18381211]
 [-1.02184904 -1.2833891  -1.3154443 ]
 [-1.74885626 -1.34022653 -1.3154443 ]
 [-1.14301691 -1.2833891  -1.44707648]]


In [114]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.set_printoptions(
    precision=8, suppress=True, edgeitems=5, linewidth=200
)
np.random.seed(42)
df = pd.read_csv('pca.csv')

X = df.copy()
y = X.pop('class')

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

eig_vals,eig_vecs=np.linalg.eig(np.cov(X_std.T))
eig_pairs=[(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort(reverse=True) 
W=np.hstack((eig_pairs[0][1].reshape(3,1),eig_pairs[1][1].reshape(3,1)))
X_pca=X_std.dot(W)  
df_pca=pd.DataFrame(data=X_pca,columns=['pca_1','pca_2'])
df_pca['pca_2']=-df_pca['pca_2']
df_pca['class']=y
print(df_pca[:10])

       pca1      pca2  class
0 -2.060360 -0.298674    0.0
1 -2.195981 -0.101727    0.0
2 -2.365221  0.080749    0.0
3 -2.365794  0.208165    0.0
4 -2.128171 -0.200201    0.0
5 -1.603256 -0.412703    0.0
6 -2.323005  0.262683    0.0
7 -2.094552 -0.185730    0.0
8 -2.535034  0.390641    0.0
9 -2.238771 -0.156245    0.0


In [118]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


np.set_printoptions(
    precision=8, suppress=True, edgeitems=5, linewidth=200
)
np.random.seed(42)
df = pd.read_csv('pca.csv')

X = df.copy()
y = X.pop('class')

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

pca=PCA(n_components=2)
X_pca=pca.fit_transform(X_std)
df_pca=pd.DataFrame(data=X_pca,columns=['pca_1','pca_2'])
df_pca['class']=y
print(df_pca[:10])

      pca_1     pca_2  class
0 -2.060360 -0.298674    0.0
1 -2.195981 -0.101727    0.0
2 -2.365221  0.080749    0.0
3 -2.365794  0.208165    0.0
4 -2.128171 -0.200201    0.0
5 -1.603256 -0.412703    0.0
6 -2.323005  0.262683    0.0
7 -2.094552 -0.185730    0.0
8 -2.535034  0.390641    0.0
9 -2.238771 -0.156245    0.0


In [135]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df=pd.read_csv('pca.csv')
scaler=StandardScaler()
X_scaled=scaler.fit_transform(df)
pca=PCA(n_components=3)
X_pca=pca.fit_transform(X_scaled)
explained_variance=pca.explained_variance_ratio_
#print(type(explained_variance))
result=pd.DataFrame(data=explained_variance,columns=['expained_variance_ratio'])
result['cumulative']=result.expained_variance_ratio.cumsum()
result['component']=result.index+1
print(result)

   expained_variance_ratio  cumulative  component
0                 0.357832    0.357832          1
1                 0.168064    0.525896          2
2                 0.142732    0.668627          3


In [138]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

df=pd.read_csv('pca.csv')
scaler=StandardScaler()
X_scaled=scaler.fit_transform(df)
pca=PCA(n_components=0.95)
X_pca=pca.fit_transform(X_scaled)   
print('Liczba komponentów:',pca.n_components_)

Liczba komponentów: 8
